---
title: "0924Est"
output: html_document
date: '2023-09-24'
---

```{r setup, include=FALSE}
library(foreach)
library(doParallel)
library(stats)
library(ggplot2)
library(ks)
library(tidyverse)
library(rv)
library(R.utils)
library(segmented)
library(rootSolve)
library(gridExtra)
library(cowplot)
library(evmix)
homedir='~/R/MFsampling'
#homedir='.'
scriptsdir <- file.path(homedir, "scripts")
sourceDirectory(scriptsdir, recursive=TRUE, modifiedOnly=FALSE, verbose=TRUE)

```

# 1. Setup


# 1. Setup

```{r eval=F}
set_x_env(type="heavyTail")
set_model(type="p1",a=3)
pX_unnorm <- Vectorize(mprime) 
noise_sigma=6
noise_type <- "homo"  # noiseless, homo, or hetero
sigma=set_param(noise_type, noise_sigma = noise_sigma)
set_y_env(noise_type)
plot_sampler(XY_sampler(10^3))

curve(log(fY(x)),from=-70,to=70)
```

```{r eval=F}
N=10^6;r=25;n=150
data1 = IS_sampler(N,r=r,n=n, true_FX = F)
xLR = data.frame(xL=xL, xR=xR, type="known m")
data1 %>% mutate(type="known m") %>%
  ggplot() + geom_point(aes(x_vec,y_vec)) +
  geom_vline(data= xLR %>% pivot_longer(1:2, values_to = "xLR",names_to = "trType"),aes(xintercept = xLR, color="xL/xR"),linetype='dashed') +
  scale_colour_manual(values=c("red"), labels=c("xL,xR"))+
  labs(color="") +xlab("X")+ylab("Y") + facet_grid(~type)+
  geom_line(data=data.frame(x = seq(mean(xLR$xL),mean(xLR$xR),length.out = 100 ))%>%
              mutate("known m"=m(x)) %>%
              pivot_longer(c("known m"), names_to = "type", values_to = "y"), aes(x,y))+
  theme(
    legend.direction="horizontal",
    text=element_text(size=12),
    legend.title=element_text(size=12),
    legend.text=element_text(size=12),
    legend.background = element_rect(fill="transparent"),
    strip.text.x = element_text(size=12)
  )
```


## m1 - homoscedastic

```{r eval=F}
set_x_env(type="heavyTail")
set_model(type="p1", a=3)
pX_unnorm <- Vectorize(mprime)
noise_sigma=6
noise_type <- "homo"  # noiseless, homo, or hetero
sigma=set_param(noise_type, noise_sigma = noise_sigma)
set_y_env(noise_type)
y_grid = seq(-100,100, length.out=400)
results = generate_ldens(y_grid,m_idx="p1",noise_type,r=25,n=150, N = 6*10^6, noise_sigma = noise_sigma, plr=T)
```

## m1 -- comparing N0 and optimality

```{r}
set_x_env(type="heavyTail")
set_model(type="p1", a=3) 
pX_unnorm <- Vectorize(mprime) 
noise_sigma=0
noise_type <- "noiseless"  # noiseless, homo, or hetero
sigma=set_param(noise_type, noise_sigma = noise_sigma)
set_y_env(noise_type)
y_grid = seq(-80,80, length.out=400)
results = generate_ldens(y_grid,m_idx="p1",noise_type,r=25,n=150, N =10^6, noise_sigma = noise_sigma, plr=F)

set_x_env(type="heavyTail")
set_model(type="p1", a=3) 
pX_unnorm <- Vectorize(mprime)
noise_sigma=6
noise_type <- "homo"  # noiseless, homo, or hetero
sigma=set_param(noise_type, noise_sigma = noise_sigma)
set_y_env(noise_type)
y_grid = seq(-80,80, length.out=400)
results = generate_ldens(y_grid,m_idx="p1",noise_type,r=25,n=150, N =10^5, noise_sigma = noise_sigma, plr=F)
results = generate_ldens(y_grid,m_idx="p1",noise_type,r=25,n=150, N =10^6, noise_sigma = noise_sigma, plr=F)
```



## m2 -- density

```{r eval=F}
## Parameters to set
noise_sigma=6
set_x_env(type="normal")
set_model(type="non_monotone",a=1.2,b=10) 
noise_type <- "homo"  # noiseless, homo, or hetero
sigma=set_param(noise_type, noise_sigma = noise_sigma)
set_y_env(noise_type, is_monotone = F)
pX_unnorm <- build_pX_hat(m, fYtilde, fX, xlim=c(-10,10), normalize=F)
y_grid = seq(-90,90, length.out=500)
results = generate_ldens(y_grid,m_idx="PM",noise_type,r=25,n=150, N = 10^6, noise_sigma = noise_sigma, plr=T)

```



## Figure 0:  m1, m2 trend 

```{r }
set_x_env(type="heavyTail")
set_model(type="p1",a=3) 
pX_unnorm <- Vectorize(mprime) 
noise_sigma=6
noise_type <- "homo"  # noiseless, homo, or hetero
sigma=set_param(noise_type, noise_sigma = noise_sigma)
set_y_env(noise_type)

m1<-m
N=6*10^6;r=25;n=150
data1 = IS_sampler(N,r=r,n=n, true_FX = F)
xLR = data.frame(xL=xL, xR=xR, type="known m", m="m1")
data2 = IS_sampler(N,r=r,n=n, type='plr', true_FX = F)
xLR = rbind(xLR,data.frame(xL=xL, xR=xR, type="PLR", m="m1"))
o1 = fit_plr(data2 %>% mutate(x=x_vec,y=y_vec))

noise_sigma=6
set_x_env(type="normal")
set_model(type="non_monotone",a=1.2,b=10) 
noise_type <- "homo"  # noiseless, homo, or hetero
sigma=set_param(noise_type, noise_sigma = noise_sigma)
set_y_env(noise_type, is_monotone = F)
pX_unnorm <- build_pX_hat(m, fYtilde, fX, xlim=c(-10,10), normalize=F)
m2<-m
N=10^6;r=25;n=150
#data3 = IS_sampler(N,r=r,n=n, true_FX = F)
data3=data1
xLR = rbind(xLR,data.frame(xL=xL, xR=xR, type="known m", m="m2"))
data4=data2
#data4 = IS_sampler(N,r=r,n=n, type='plr', true_FX = F)
xLR = rbind(xLR,data.frame(xL=xL, xR=xR, type="PLR", m="m2"))
o2 = fit_plr(data4 %>% mutate(x=x_vec,y=y_vec))

fig=1
p=rbind(data1 %>% mutate(type="known m", m="m1"), data2 %>% mutate(type="PLR", m="m1"),
      data3 %>% mutate(type="known m", m="m2"), data4 %>% mutate(type="PLR", m="m2")) %>%
  filter(m==sprintf("m%d",fig)) %>%
  ggplot() + geom_point(aes(x_vec,y_vec)) +
  geom_vline(data= xLR %>% pivot_longer(1:2, values_to = "xLR",names_to = "trType") %>% filter(m==sprintf("m%d",fig)),aes(xintercept = xLR, color="xL/xR"),linetype='dashed') +
  scale_colour_manual(values=c("red"), labels=c("xL,xR"))+
  labs(color="") +xlab("X")+ylab("Y") + facet_grid(~m+type)+
  geom_line(data= rbind(data.frame(x = seq(mean((xLR %>% filter(m=="m1"))$xL),mean((xLR %>% filter(m=="m1"))$xR),length.out = 100 ))%>% 
                          mutate("known m"=m1(x),"PLR"=predict(o1, data.frame(x=x)), m="m1"),
                        data.frame(x = seq(mean((xLR %>% filter(m=="m2"))$xL),mean((xLR %>% filter(m=="m2"))$xR),length.out = 100 ))%>%
                          mutate("known m"=m2(x),"PLR"=predict(o2, data.frame(x=x)), m="m2")) %>%
              filter(m==sprintf("m%d",fig)) %>%
              pivot_longer(c("known m","PLR"), names_to = "type", values_to = "y"), aes(x,y))+
  theme(
    legend.position="None",
    text=element_text(size=12),
    legend.title=element_text(size=12),
    legend.text=element_text(size=12),
    legend.background = element_rect(fill="transparent"),
    strip.text.x = element_text(size=12),
    strip.placement=ifelse(fig==2,"outside","inside")
  )

ggsave(filename=sprintf("./final/f0m%d.png",fig), plot=p, width=853/(96*2), height=278/96, dpi=96)
```

## m3 -- density

```{r eval=F}
## True distribution follows m3, but treat it as homoscedastic
set_x_env(type="normal",x_mean = 5)
set_model(type="hetero", a=1,b=2) 
noise_type <- "hetero"  # noiseless, homo, or hetero
sigma=set_param(noise_type)
set_y_env(noise_type, a=1,b=2)
pX_unnorm <- Vectorize(mprime)
y_grid = seq(1e-8,180, length.out=600)
#plot_sampler(XY_sampler(10^3))+geom_hline(aes(yintercept=0))
results = generate_ldens(y_grid,m_idx="hetero-homo",noise_type="homo",r=25, n=150, N = 10^6)

## True distribution follows m3, and estimate using heteroscedastic method
h<-0.15
Nbreaks<-3
sample_y = sample_z
mprime <- mtilde_prime
pX_unnorm <- mtilde_prime
fZ=function(x){fY(exp(x))/beta_prime(exp(x))}
results = generate_ldens(y_grid,m_idx="hetero",noise_type="hetero",r=25, n=150, N = 10^6)
```


## m3 -- optimality

```{r }
## m3 noiseless
# set_x_env(type="normal",x_mean = 5)
# set_model(type="hetero", a=1,b=2) 
# noise_type <- "noiseless"  # noiseless, homo, or hetero
# noise_sigma=0
# sigma=set_param(noise_type, noise_sigma = noise_sigma)
# set_y_env(noise_type)
# h=2
# pX_unnorm <- Vectorize(mprime)
# y_grid = seq(-10,180, length.out=600)
# results = generate_ldens(y_grid,m_idx="exp",noise_type,r=25,n=150, N = 10^6, noise_sigma = noise_sigma, plr=F)

## m3 homoscedastic setting
set_x_env(type="normal",x_mean = 5)
set_model(type="hetero", a=1,b=2) 
noise_type <- "homo"  # noiseless, homo, or hetero
noise_sigma=6
sigma=set_param(noise_type, noise_sigma = noise_sigma)
set_y_env(noise_type,ytlim = c(0))
ytlim=c(0)
pX_unnorm <- Vectorize(mprime)
y_grid = seq(-10,180, length.out=600)
results = generate_ldens(y_grid,m_idx="exp-homo",noise_type,r=25,n=150, N = 10^6, noise_sigma = noise_sigma, plr=F)

```




## Figure 0:  m3 trend

```{r eval=F}
set_x_env(type="normal",x_mean = 5)
set_model(type="hetero", a=1,b=2) 
noise_type <- "hetero"  # noiseless, homo, or hetero
sigma=set_param(noise_type)
set_y_env(noise_type, a=1,b=2)
pX_unnorm <- Vectorize(mprime)
m1<-m
N=10^6;r=25;n=150
data1 = IS_sampler(N,r=r,n=n, true_FX = F)
xLR = data.frame(xL=xL, xR=xR, type="known m", m="m3 - Y")
data2 = IS_sampler(N,r=r,n=n, type='plr', true_FX = F)
xLR = rbind(xLR,data.frame(xL=xL, xR=xR, type="PLR", m="m3 - Y"))
o1 = fit_plr(data2 %>% mutate(x=x_vec,y=y_vec))

sample_y = sample_z
mprime <- mtilde_prime
pX_unnorm <- mtilde_prime
m2<-function(x){x/2}
N=10^6;r=25;n=150
data3 = IS_sampler(N,r=r,n=n, true_FX = F)
xLR = rbind(xLR,data.frame(xL=xL, xR=xR, type="known m", m="m3 - Z"))
data4 = IS_sampler(N,r=r,n=n, type='plr', true_FX = F)
xLR = rbind(xLR,data.frame(xL=xL, xR=xR, type="PLR", m="m3 - Z"))
o2 = fit_plr(data4 %>% mutate(x=x_vec,y=y_vec))

fig="Y"
p=rbind(data1 %>% mutate(type="known m", m="m3 - Y"), data2 %>% mutate(type="PLR", m="m3 - Y"),
      data3 %>% mutate(type="known m", m="m3 - Z"), data4 %>% mutate(type="PLR", m="m3 - Z")) %>% filter(m==sprintf("m3 - %s",fig)) %>%
  ggplot() + geom_point(aes(x_vec,y_vec)) +
  geom_vline(data= xLR %>% filter(m==sprintf("m3 - %s",fig)) %>% pivot_longer(1:2, values_to = "xLR",names_to = "trType"),aes(xintercept = xLR, color="xL/xR"),linetype='dashed') +
  scale_colour_manual(values=c("red"), labels=c("xL,xR"))+
  labs(color="") +xlab("X")+ylab(fig) + facet_grid(~m+type)+
  geom_line(data=rbind(data.frame(x = seq(mean((xLR %>% filter(m=="m3 - Y"))$xL),mean((xLR %>% filter(m=="m3 - Y"))$xR),length.out = 100 ))%>%
              mutate("known m"=m1(x),"PLR"=predict(o1, data.frame(x=x)), m="m3 - Y"), data.frame(x = seq(mean((xLR %>% filter(m=="m3 - Z"))$xL),mean((xLR %>% filter(m=="m3 - Z"))$xR),length.out = 100 ))%>%
              mutate("known m"=m2(x),"PLR"=predict(o2, data.frame(x=x)), m="m3 - Z")) %>%
              pivot_longer(c("known m","PLR"), names_to = "type", values_to = "y") %>% filter(m==sprintf("m3 - %s",fig)), aes(x,y))+
  theme(
    legend.position="None",
    text=element_text(size=12),
    legend.title=element_text(size=12),
    legend.text=element_text(size=12),
    legend.background = element_rect(fill="transparent"),
    strip.text.x = element_text(size=12)
  )
ggsave(filename=sprintf("./final/f0m3%s.png",fig), plot=p, width=853/(96*2), height=278/96, dpi=96)
```


